# Generated by Django 4.1.5 on 2023-05-06 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_alter_user_is_employee"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="is_employee",
        ),
    ]
