# Generated by Django 4.1.5 on 2023-05-30 02:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("weapons", "0007_alter_weapon_tipe"),
        ("comments", "0003_comment_product"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="comment",
            name="product",
        ),
        migrations.AddField(
            model_name="comment",
            name="weapon",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="Comments",
                to="weapons.weapon",
            ),
            preserve_default=False,
        ),
    ]
