# Generated by Django 4.1.5 on 2023-04-18 22:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("atributes", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Weapon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("tipe", models.CharField(max_length=20)),
                ("price", models.IntegerField()),
                ("descripition", models.TextField(max_length=600)),
                ("image", models.CharField(max_length=200)),
                ("image2", models.CharField(max_length=200)),
                ("image3", models.CharField(blank=True, max_length=200)),
                (
                    "group",
                    models.CharField(
                        choices=[
                            ("Guns", "Guns"),
                            ("Knife", "Knife"),
                            ("Bow", "Bow"),
                            ("CrossBow", "Crossbow"),
                            ("Uniformed", "Uninformed"),
                        ],
                        default="Uniformed",
                        max_length=10,
                    ),
                ),
                (
                    "atributes",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="atributes",
                        to="atributes.atributes",
                    ),
                ),
            ],
        ),
    ]
