# Generated by Django 4.1.5 on 2023-04-19 01:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("atributes", "0001_initial"),
        ("weapons", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="weapon",
            name="atributes",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="atributes",
                to="atributes.atributes",
            ),
        ),
    ]
