# Generated by Django 4.1.5 on 2023-05-03 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("weapons", "0003_alter_weapon_atributes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="weapon",
            name="descripition",
            field=models.TextField(max_length=1000),
        ),
    ]
