# Generated by Django 4.1.5 on 2023-04-19 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("atributes", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="atributes",
            old_name="calibre",
            new_name="caliber",
        ),
        migrations.RenameField(
            model_name="atributes",
            old_name="capacidade",
            new_name="capacity",
        ),
        migrations.RenameField(
            model_name="atributes",
            old_name="comprimento",
            new_name="length",
        ),
        migrations.RenameField(
            model_name="atributes",
            old_name="peso",
            new_name="system",
        ),
        migrations.RenameField(
            model_name="atributes",
            old_name="sistem",
            new_name="weight",
        ),
    ]
