# Generated by Django 4.1.5 on 2023-04-19 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("atributes", "0002_rename_calibre_atributes_caliber_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="atributes",
            name="finishing",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="atributes",
            name="model",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="atributes",
            name="operation",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
